version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/skm
    binary: skm
    ldflags:
      - -s -w
      - -X github.com/ejoy/skm/internal/cli.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "skm_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"

release:
  github:
    owner: wujiyu115
    name: skm
